## <b>COLUMN TRANSFORMER </b>

In [108]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder
from sklearn.impute import SimpleImputer

In [109]:
df=pd.read_csv('Student_performance_10k.csv')

In [110]:
df.sample(5)

roll_no  gender race_ethnicity parental_level_of_education  lunch  \
227    std-228    male        group D            some high school    1.0   
4626  std-4627    male        group E          associate's degree    0.0   
7203  std-7204  female        group C             master's degree    0.0   
7973  std-7974  female        group E                some college    0.0   
9693  std-9694  female        group C             master's degree    1.0   

      test_preparation_course math_score  reading_score  writing_score  \
227                       1.0         74           66.0           51.0   
4626                      0.0         22           40.0           54.0   
7203                      1.0         56           76.0           75.0   
7973                      0.0         83           73.0           91.0   
9693                      1.0         67           89.0           83.0   

      science_score  total_score grade  
227            80.0        271.0     B  
4626           47.0        163.0     D  
7203           84.0        291.0     B  
7973           72.0        319.0     B  
9693           62.0        301.0     B

In [111]:
df=pd.read_csv('Student_performance_10k.csv')
df['race_ethnicity'].unique()
map_values = {
    'C': 'group C',
    'group C': 'group C',
    'group C\n': 'group C',  # Note single backslash for actual newline
    'A': 'group A',
    'E': 'group E',
    'D': 'group D',
    'B': 'group B',
    'group A':'group A',
    'group B':'group B',
    'group C':'group C',
    'group D':'group D',
    'group E':'group E'
}
df['race_ethnicity'] = df['race_ethnicity'].map(map_values)

In [112]:
df['race_ethnicity'].unique()

array(['group D', 'group B', 'group C', 'group E', 'group A', nan],
      dtype=object)

In [113]:
df.dropna(axis=0,inplace=True,subset=['race_ethnicity','lunch','gender','roll_no','test_preparation_course','parental_level_of_education'])

In [114]:
map_values = {
    'male': 'male',
    '\\tmale': 'male',
    'female': 'female',
    'Boy': 'male',
    'Girl': 'female',
}
    
df['gender'] = df['gender'].map(map_values)

In [115]:
df['gender'].unique()

array(['male', 'female'], dtype=object)

In [116]:
df.isnull().sum()

roll_no                         0
gender                          0
race_ethnicity                  0
parental_level_of_education     0
lunch                           0
test_preparation_course         0
math_score                     23
reading_score                  24
writing_score                  24
science_score                  23
total_score                    19
grade                           3
dtype: int64

In [117]:
print(np.round(df.describe()))
print(len(df))


        lunch  test_preparation_course  reading_score  writing_score  \
count  9888.0                   9888.0         9864.0         9864.0   
mean      1.0                      0.0           70.0           71.0   
std       0.0                      0.0           19.0           18.0   
min       0.0                      0.0           17.0           10.0   
25%       0.0                      0.0           57.0           59.0   
50%       1.0                      0.0           71.0           73.0   
75%       1.0                      1.0           85.0           85.0   
max       1.0                      1.0          100.0          100.0   

       science_score  total_score  
count         9865.0       9869.0  
mean            66.0        265.0  
std             19.0         42.0  
min              9.0         89.0  
25%             53.0        237.0  
50%             67.0        268.0  
75%             81.0        295.0  
max            100.0        383.0  
9888


In [118]:
df['reading_score'].unique()

array([ 38., 100.,  99.,  51.,  58.,  49.,  80.,  53.,  nan,  70.,  97.,
        96.,  82.,  76.,  73.,  68.,  71.,  57.,  54.,  89.,  69.,  67.,
        77.,  66.,  81.,  43.,  56.,  90.,  98.,  63.,  64.,  86.,  88.,
        40.,  62.,  30.,  60.,  65.,  85.,  91.,  37.,  78.,  84.,  79.,
        74.,  95.,  47.,  59.,  48.,  92.,  44.,  72.,  17.,  34.,  87.,
        41.,  36.,  50.,  52.,  83.,  46.,  45.,  93.,  75.,  39.,  94.,
        55.,  61.,  35.,  33.,  31.,  26.,  42.,  24.,  21.,  25.,  23.,
        27.,  22.,  20.,  32.,  19.,  28.,  18.,  29.])

In [119]:
df['math_score'].unique()

array(['89', '65', '10', '22', '26', '40', '25', nan, '29', '18', '72',
       '23', '35', '38', '41', '44', '39', '47', '37', '49', '11', '32',
       '85', '78', '68', '64', '60', '69', '87', '83', '42', '51', '75',
       '20', '81', '98', '100', '24', '71', '82', '55', '19', '48', '34',
       '74', '28', '43', '62', '21', '93', '66', '0', '46', '13', '45',
       '57', '54', '70', '30', '97', '50', '61', '73', '88', '36', '33',
       '76', '27', '17', '16', '56', '80', '53', '14', '58', '9', '8',
       '79', '12', '77', '52', '99', '67', '59', '63', '86', '31', '92',
       '94', '6', '91', '96', '84', '95', '15', '90', '7', '4', '\\t41',
       '5'], dtype=object)

In [120]:
df['science_score'].unique()

array([ 26.,  96.,  58.,  84.,  65.,  48.,  17.,  55.,  91.,  45.,  nan,
        54.,  73.,  75.,  47.,  78.,  46.,  82.,  81.,   9.,  31.,  70.,
        57.,  71.,  99.,  67.,  60.,  94.,  28.,  61.,  79.,  72., 100.,
        51.,  74.,  52.,  56.,  33.,  36.,  90.,  53.,  88.,  93.,  66.,
        62.,  59.,  27.,  23.,  15.,  10.,  42.,  77.,  83.,  50.,  80.,
        38.,  49.,  40.,  69.,  43.,  64.,  97.,  39.,  86.,  25.,  41.,
        34.,  89.,  44.,  32.,  87.,  98.,  63.,  85.,  35.,  68.,  30.,
        29.,  13.,  92.,  37.,  11.,  12.,  76.,  95.,  18.,  22.,  14.,
        21.,  24.,  19.,  20.,  16.])

In [121]:
df['total_score'].unique()

array([238., 328., 264., 198., 213., 206., 156., 228., 293., 162., 289.,
        nan, 283., 280., 224., 208., 195., 237., 240., 233., 242., 306.,
       178., 169., 247., 292., 319., 215., 313., 297., 212., 241., 311.,
       253., 272., 257., 284., 270., 266., 230., 369., 221., 288., 302.,
       268., 301., 249., 210., 165., 176., 285., 246., 182., 307., 304.,
       229., 231., 255., 256., 305., 243., 287., 188., 193., 327., 340.,
       191., 220., 218., 273., 314., 197., 225., 321., 300., 203., 172.,
       234., 217., 335., 320., 324., 166., 317., 294., 282., 140., 274.,
       352., 281., 252., 310., 265., 192., 239., 183., 194., 204., 308.,
       258., 309., 296., 199., 275., 262., 269., 190., 322., 267., 124.,
       248., 219., 207., 201., 226., 254., 250., 196., 260., 171., 236.,
       235., 227., 146., 211., 271., 214., 205., 277., 232., 216., 209.,
       263., 318., 185., 355., 278., 325., 261., 164., 222., 157., 147.,
       330., 179., 115., 291., 295., 371., 303., 36

In [122]:
df['math_score']=df['math_score'].replace('\\t41',41)

In [123]:
ie=SimpleImputer()
ie.fit(df[['math_score','science_score','total_score','reading_score','writing_score']])

SimpleImputer()

Here with the simpleImputer all the missing values are replaced with mean

In [124]:
imputed_datas=ie.transform(df[['math_score','science_score','total_score','reading_score','writing_score']])

In [125]:
imputed_datas

array([[ 89.,  26., 238.,  38.,  85.],
       [ 65.,  96., 328., 100.,  67.],
       [ 10.,  58., 264.,  99.,  97.],
       ...,
       [ 70.,  90., 331.,  71., 100.],
       [ 87.,  89., 336.,  60., 100.],
       [ 31.,  80., 293.,  89.,  93.]])

In [126]:
print(len(imputed_datas))

9888


We would do all the other encodings and other things like that one by one and later we have to concatenate all the arrays. Thus column transformere can be done in the further steps rather than doing one by one. 
### COLUMN TRANSFORMER

In [127]:
df['parental_level_of_education'].unique()

array(['some college', 'high school', "master's degree",
       "associate's degree", 'some high school', "bachelor's degree"],
      dtype=object)

In [128]:
df['grade'].unique()

array(['C', 'A', 'B', 'D', nan, 'Fail'], dtype=object)

In [129]:
df['grade'].fillna(df['grade'].mode()[0],inplace=True)

C:\Users\Acer\AppData\Local\Temp\ipykernel_9228\671689149.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['grade'].fillna(df['grade'].mode()[0],inplace=True)


In [130]:
df['grade'].unique()

array(['C', 'A', 'B', 'D', 'Fail'], dtype=object)

In [131]:
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['reading_score','writing_score','science_score','math_score','total_score']),
    ('tnf2',OrdinalEncoder(categories=[['some high school','high school','some college',"bachelor's degree","associate's degree","master's degree"],['Fail','A','B','C','D']]),['parental_level_of_education','grade']),
    ('tnf3',OneHotEncoder(drop='first'),['gender','race_ethnicity'])
    ],
    remainder='passthrough')

In [132]:
new_df=df[['race_ethnicity','gender','grade','reading_score','writing_score','science_score','total_score','math_score','parental_level_of_education']]

In [133]:
ct.fit_transform(new_df)

array([[ 38.,  85.,  26., ...,   0.,   1.,   0.],
       [100.,  67.,  96., ...,   0.,   0.,   0.],
       [ 99.,  97.,  58., ...,   1.,   0.,   0.],
       ...,
       [ 71., 100.,  90., ...,   0.,   0.,   0.],
       [ 60., 100.,  89., ...,   0.,   0.,   0.],
       [ 89.,  93.,  80., ...,   0.,   0.,   0.]])

With the column transformer we can do all the preprocesssing at once making a composite transformer.